services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/var/www/certbot
      - ./certs:/etc/letsencrypt
    depends_on:
      - chatapi
      - notificationapi
      - userapi
    networks:
      - backend

  chatapi:
    build:
      context: .
      dockerfile: UserChatAPI/Dockerfile
    container_name: chatapi
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=ChatDb;User Id=sa;Password=Your_strong_password123;
    depends_on:
      - db
    networks:
      - backend

  notificationapi:
    build:
      context: .
      dockerfile: NotificationApi/Dockerfile
    container_name: notificationapi
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=NotificationDb;User Id=sa;Password=Your_strong_password123;
    depends_on:
      - db
    networks:
      - backend

  userapi:
    build:
      context: .
      dockerfile: ChatAppAPI/Dockerfile
    container_name: userapi
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=UserDb;User Id=sa;Password=Your_strong_password123;
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_password123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./www:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot
      -w /var/www/certbot
      -d chat.fastchat1005.xyz
      -d notification.fastchat1005.xyz
      -d user.fastchat1005.xyz
      --email hqhuyzzz012@gmail.com --agree-tos --no-eff-email --non-interactive"

networks:
  backend:
    driver: bridge

volumes:
  sql_data: